version: "3"
services:
  mc:
    image: itzg/minecraft-server
    ports:
      - 25565:25565
      - 19132:19132
      - 19132:19132/udp
    environment:
      EULA: "TRUE"
      VERSION: "1.19.3"
      TYPE: "PAPER"
      MEMORY: "8G"
      ENABLE_ROLLING_LOGS: "true"
      JVM_XX_OPTS: "-XX:MaxMetaspaceSize=1G"
    logging:
      driver: gcplogs
      options:
        gcp-meta-name: mc
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      - /home/okamoto_shinichi/docker-papermc/mc:/data
